Home Highlighted Events
ubc-biztech/bt-mobile pull request #27
Opened 2020-10-06 00:53 UTC by phillytan

**Changelogs:**
- Add Featured Event + Next Event in Homepage
- Fixed call on getting a user's registered events

Closes #16

2021-01-30 03:30 UTC, adindotdev requested changes

2021-01-30 03:30 UTC, adindotdev commented on lib/home/home.dart
> +              headline: 'Your Next Event',
Should be in the constants file.

2021-01-30 03:30 UTC, adindotdev commented on lib/home/home_presenter.dart
> +    await _eventsManager.loadEvents();
Called also on line 130 -> look to abstract?

2021-01-30 03:30 UTC, adindotdev commented on lib/common/user.dart
> +      Map<String, dynamic> responseData = await Fetcher().fetchBackend(
Ambiguous variable name.

2021-03-13 17:12 UTC, jindazhao commented
lib/events/events_presenter.dart has extra space not letting check pass please fix

2024-09-26 03:44 UTC, closed without merging

2024-09-26 03:44 UTC, voctory commented
Closing stale PRs in `ubc-biztech` org