Feature/events load
ubc-biztech/bt-mobile pull request #30
Opened 2021-01-24 18:26 UTC by jindazhao

Confirm Sign Out Button and implementation works.

Created new strings for confirmation of signing out.

2021-01-24 18:33 UTC, jindazhao commented
It builds fine locally I'm not sure why it's failing one of the tests

2021-01-30 02:44 UTC, adindotdev commented
I think you're missing a file, did you `git add` everything?

2021-01-30 03:10 UTC, adindotdev requested changes

2021-01-30 03:10 UTC, adindotdev commented on lib/constants/strings.dart
> +  static const String confirmSignOutTitle = 'Confirm Sign Out?';
Change copy.

2021-01-30 03:10 UTC, adindotdev commented on lib/profile/profile.dart
> +            // ProfileSignOutDialog(onConfirmedPressed: widget.presenter.onConfirmButtonPressed),
Remove commented lines.

2021-01-30 03:10 UTC, adindotdev commented on lib/profile/profile_presenter.dart
> +          ProfileSignOutDialog(onConfirmedPressed: onConfirmButtonPressed),
File including ProfileSignOutDialog widget is missing.

2021-01-30 19:32 UTC, jindazhao commented
I pushed with the new updates but still unsure as to why the build is failing

2021-02-06 03:24 UTC, closed without merging